### ISSUE TITLE
Give the Component render function access to props

### ISSUE THREAD

**Issue by wereHamster** [wereHamster/nauva#8]
The Component render function has only access to the state. That means when you need access to props, you need inject the props into the state. In many cases this is rather tedious (similar to the `NOP` actions which I made obsolete by changing the type of side effects from `IO a` to `IO (Maybe a)`).

For example, the `linkComponent` is defined as:

```haskell
linkComponent :: Component LinkProps () LinkProps ()
linkComponent = Component
    { ...
    , initialComponentState = \props -> pure (props, [])
    , receiveProps = \props _ -> pure (props, [], [])
    , renderComponent = \(LinkProps {..}) -> with element [onClick_ onClickHandler]
    , ...
    }
```

It doesn't keep any local state (it's only a component so it can emit side effects), but the render function needs access to the props. So the props are mapped straight into state. Meh.

I'm undecided whether this would be a good move. On one hand, I like that the render function has only one argument, and it's obvious from the code how the state is updated (what kinds of inputs/events/actions affect it). On the other hand, it's very tedious having to map the props into state (boilerplate code).

My suspicion is that even if the render function requires access to only a subset of the props, people are most likely not going to extract just the things they need and simply map everything into the state, which is equivalent to giving the render function direct access to both. Example:

```haskell
data MyProps = MyProps { ... }
data MyState = MyState { props :: MyProps, ... }

myComponent :: Component MyProps () MyState ()
myComponent = Component
    { ...
    , receiveProps = \props s -> pure (s { props = props }, [], [])
    , ...
    }
```

One downside which I can see is that it will make it more difficult to implement a `shouldComponentUpdate` later on (if we decide to, not sure it's really necessary). Because with this change suddenly the render function may depend on stuff it doesn't really need, and the component itself has no way of removing unnecessary data from its arguments. We could always tell users to re-wrap the necessary data in a new object and use a `Thunk`, but then we're simply shifting complexity around.

So... 👍  or 👎 ? Please vote.

**Comment by grossbart** [comment]
Coming from React, my mental model of `props` and `state` is the following:

* `props` are the data that the component should render. They are passed in from the outside.
* `state` describes the internal state of the component. It is not visible to the outside.

In a system like [Om](https://github.com/omcljs/om) there is no distinction between the two, because there is no internal state – everything lives in a root state. This is powerful because it allows Om to serialize its state and precisely rehydrate the app from such a representation. A similar-ish approach has been taken in [Cycle Onionify](https://github.com/staltz/cycle-onionify).

So, my answer depends on the model to follow 😄 For a React-like model I think it's necessary to pass in both props and state to the render function, this has proven to work well. For a root state approach only one argument is needed because there is nothing internal to the render function.

Alternatively, I liked to write the render functions in our Purescript project like so: `myComponent :: forall a. Name -> Age -> Html a`. This makes it very explicit what arguments are passed in and I like that. Doesn't work for more complex components that require a variadic interface such as React's props provides – but maybe that would call for more powerful ways to compose instead of adding more fields to a bag of props?

**Comment by wereHamster** [comment]
Both forms are isomorphic. Remember, any function which takes two arguments can be converted to one which takes one argument (a tuple) and vice versa. See [curry](http://hackage.haskell.org/package/base-4.9.0.0/docs/Prelude.html#v:curry) and [uncurry](http://hackage.haskell.org/package/base-4.9.0.0/docs/Prelude.html#v:uncurry).

The question is therefore less about which form is 'necessary' (because they are both equivalent), but rather which one is more convenient to the developer, while still providing useful abstractions.

The idea that developers have to write the equivalent of

```javascript
componentWillReceiveProps(props) {
    this.setState({ props });
}
```

whenever they want to access props in the render function of a component will not fare well. It's boilerplate. Nobody likes boilerplate.

The downside that I mentioned is the only one I can think of. And it's not that bad if we can't implement `shouldComponentUpdate` for a Nauva component. Let me explain:

React has only one kind of Component and it supports many different features: local state, shouldComponentUpdate, lifecycle events (will mount, will unmount), refs etc. But if I think about how we've used React components, it's for two (usually distinct) reasons:

 - Optimization / shouldComponentUpdate.
 - Local state: to be able to react to internal (DOM events generated by children) and external (global DOM events, onpopstate, websocket messages etc) inputs.

And Nauva already makes a distinction between the two: `EThunk` (optimization) and `EComponent` (local state). So I'm inclined to not implement `shouldComponentUpdate` (and therefore be free to pass both props and state to the render function), and if people want to take advantage of optimizations, they should use a `EThunk`.

Single responsibility principle, if you're into software patterns. The app is slow: See where you can wrap sub-trees in a `EThunk`. Need to keep local state: use a `EComponent`.

**Comment by grossbart** [comment]
There are two ways to look at `shouldComponentUpdate`: 1) it's a rendering optimization that you add when you know rerendering would be expensive, or 2) it's a computation optimization that you only add when you know you can efficiently compute whether two states are equal.

In any case: the user has to care because the program can't determine what to do by itself. But Om solved this through its immutable data structures: it always knows when state changed and can implement `shouldComponentUpdate` for free, the user doesn't have to care about this. With Nauva we're in immutable land as well, so in a way I would expect not to have to care about this either.

So, while I at first liked the distinction between `EThunk` and `EComponent`, I think that it does put the burden of optimization on the user without necessity.

**Comment by wereHamster** [comment]
The decision whether the rendering of a subtree should be optimised or not *should* be up to the user. If it's because the props type implements the `Eq` instance, or the user provides an explicit `shouldComponentUpdate` implementation, or because the user wraps a subtree in a `EThunk`… these are all different expressions of the same thing.

The problem with the `Eq` instance is that not all values are comparable: You can't compare two functions for example. If we go down that route, it would be impossible to pass functions/callbacks to components. I have no idea how Om deals with this issue, can you compare functions in clojurescript?

And sometimes you even want to *avoid* comparing two values, even if it's technically possible. Consider the case when you fetch a JSON with 10m entries. And later you fetch it again. Now even if you *could* go through all 20m entries and compare them, you shouldn't. It's too expensive, and some sort of *bounded equality check* would be more appropriate here. And whether to use Eq, a custom bounded equality check or even [reallyUnsafePtrEquality#](https://hackage.haskell.org/package/ghc-prim-0.5.0.0/docs/GHC-Prim.html#v:reallyUnsafePtrEquality-35-) needs to be up to the user.
